/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sales.invoice.view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import sales.invoice.controller.ActionHandler;
import sales.invoice.controller.salesInvoiceselectionListener;
import sales.invoice.model.invoceHeaderTableModel;
import sales.invoice.model.invoiceHeader;
import sales.invoice.model.invoiceLines;

/**
 *
 * @author Eslam.Lotfy
 */
public class InvoiceFrame extends javax.swing.JFrame {

    /**
     * Creates new form nvoiceDialoge
     */
    public InvoiceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHeader = new javax.swing.JTable();
        Newinvobtn = new javax.swing.JButton();
        Newinvobtn.addActionListener(actionHandler);
        Deletinvobtn = new javax.swing.JButton();
        Deletinvobtn.addActionListener(actionHandler);
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableIlines = new javax.swing.JTable();
        savebtn = new javax.swing.JButton();
        savebtn.addActionListener(actionHandler);
        Deletebtn = new javax.swing.JButton();
        Deletebtn.addActionListener(actionHandler);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberlabel = new javax.swing.JLabel();
        Datelabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        totallabel = new javax.swing.JLabel();
        InvoiceItems = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadimenu = new javax.swing.JMenuItem();
        loadimenu.addActionListener(actionHandler);
        saveimenu = new javax.swing.JMenuItem();
        saveimenu.addActionListener(actionHandler);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableHeader.getSelectionModel().addListSelectionListener(selectionListenerobj);
        jScrollPane1.setViewportView(TableHeader);

        Newinvobtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Newinvobtn.setText("Create New Invoice ");
        Newinvobtn.setActionCommand("Create New Invoice");
        Newinvobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewinvobtnActionPerformed(evt);
            }
        });

        Deletinvobtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Deletinvobtn.setText("Delete Invoice ");
        Deletinvobtn.setActionCommand("Delete Invoice");
        Deletinvobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletinvobtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Newinvobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Deletinvobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletinvobtn)
                    .addComponent(Newinvobtn)))
        );

        TableIlines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableIlines);

        savebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        Deletebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(savebtn)
                .addGap(94, 94, 94)
                .addComponent(Deletebtn)
                .addContainerGap(161, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(Deletebtn)))
        );

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Invoice Total");

        jLabel3.setText("Invoice Date");

        jLabel4.setText("Customer Name");

        InvoiceItems.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        InvoiceItems.setForeground(new java.awt.Color(255, 51, 51));
        InvoiceItems.setText("Invoice Items");

        jMenu1.setText("File");

        loadimenu.setText("Load File");
        jMenu1.add(loadimenu);

        saveimenu.setText("Save File");
        saveimenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveimenuActionPerformed(evt);
            }
        });
        jMenu1.add(saveimenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InvoiceItems, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(numberlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberlabel)
                            .addComponent(jLabel1))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Datelabel))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(namelabel))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totallabel))
                        .addGap(60, 60, 60)
                        .addComponent(InvoiceItems, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewinvobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewinvobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewinvobtnActionPerformed

    private void DeletinvobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletinvobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletinvobtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void saveimenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveimenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveimenuActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datelabel;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Deletinvobtn;
    private javax.swing.JLabel InvoiceItems;
    private javax.swing.JButton Newinvobtn;
    private javax.swing.JTable TableHeader;
    private javax.swing.JTable TableIlines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadimenu;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel numberlabel;
    private javax.swing.JButton savebtn;
    private javax.swing.JMenuItem saveimenu;
    private javax.swing.JLabel totallabel;
    // End of variables declaration//GEN-END:variables
   private ActionHandler actionHandler = new ActionHandler(this);
    private ArrayList<invoiceHeader> _invoiceArray;
    private ArrayList<invoiceLines> _linesArray;

    public ArrayList<invoiceLines> getLinesArray() {
        return _linesArray;
    }

    public void setLinesArray(ArrayList<invoiceLines> _linesArray) {
        this._linesArray = _linesArray;
    }

    private invoceHeaderTableModel _invoceHeaderTableModel;
    public static SimpleDateFormat simpleDate = new SimpleDateFormat("dd-MM-yyy");
    private salesInvoiceselectionListener selectionListenerobj = new salesInvoiceselectionListener(this);

    public void setInvoiceArray(ArrayList<invoiceHeader> _invoiceArray) {
        this._invoiceArray = _invoiceArray;
    }

    public invoiceHeader getInoviceObj(int code) {
        for (invoiceHeader _invheader : _invoiceArray) {
            if (_invheader.getNum() == code) {
                return _invheader;
            }
        }
        return null;
    }

    public ArrayList<invoiceHeader> getInvoiceArray() {
        return _invoiceArray;
    }

    public invoceHeaderTableModel getInvoceHeaderTableModel() {
        return _invoceHeaderTableModel;
    }

    public void setInvoceHeaderTableModel(invoceHeaderTableModel _invoceHeaderTableModel) {
        this._invoceHeaderTableModel = _invoceHeaderTableModel;
    }

    public JTable getTableHeader() {
        return TableHeader;
    }

    public JTable getTableIlines() {
        return TableIlines;
    }

    public JLabel getDatelabel() {
        return Datelabel;
    }

    public JLabel getNamelabel() {
        return namelabel;
    }

    public JLabel getNumberlabel() {
        return numberlabel;
    }

    public JLabel getTotallabel() {
        return totallabel;
    }

    public ActionHandler getActionHandler() {
        return actionHandler;
    }

    public void Displayinvoices() {
        System.out.println("_________________________________________________________");        
        for (invoiceHeader invoiceobj : _invoiceArray) {
                            System.out.println("invoiceHeader :{num="+invoiceobj.getNum()+ 
                                    ",Customer="+ invoiceobj.getCutomer()+ 
                                    ",Date="+ simpleDate.format(invoiceobj.getDate())+
                                    ",invoiceTotal="+invoiceobj.getInvoiceTotal()+"}");
                    for(invoiceLines invoiceobj2 : invoiceobj.getLines()){
                             System.out.println("\t\tinvoiceLines :{item="+invoiceobj2.getName()+
                                               ",Price=" + invoiceobj2.getPrice() + 
                                               ",Count=" + invoiceobj2.getCount() + 
                                                ",Total=" + invoiceobj2.getInvoiceLinesTotal() + "}");
                             
                                     }
                System.out.println("=========================");
        }
                System.out.println("_________________________________________________________");

    }

}
